### ISSUE TITLE
connect to cryosparc2

### ISSUE THREAD

**Issue by kylelmorris** [cryoem-uoft/cryosparc2_public#1]
Silly question, sorry. Couldn't see this on github or email guide. 

Once a worker is registered how to load the cryosparc 2 interface?

My guess was in chrome to connect via hostname:39002, this is what I get back:

"Hello World from cryosparc command core."

**Comment by kylelmorris** [comment]
I think I see the problem. watchdog_dev is failing and subsequently webapp_dev throws and error.

$ cryosparcm restart
CryoSPARC is running.
Stopping cryosparc.
command_vis: stopped
command_proxy: stopped
command_core: stopped
database: stopped
Shut down
Starting cryoSPARC System master process..
CryoSPARC is not already running.
database: started
command_core: started
  cryosparc command core startup complete.
command_vis: started
command_proxy: started
watchdog_dev: ERROR (spawn error)
webapp_dev: ERROR (no such file)
-----------------------------------------------------

CryoSPARC master started. 
 From this machine, access the webapp at
    http://localhost:39000
 From other machines on the network, access at
    http://epeius:39000

Startup can take several minutes. Point your browser to the address
and refresh until you see the cryoSPARC web interface.

**Comment by suhaildawood** [comment]
Sorry for the delay! The web application should be available at `localhost:39000`. Since you're running a production instance of cryoSPARC v2, the `*_dev` processes do not need to be running.

**Comment by kylelmorris** [comment]
Thanks for writing. I started the worker on the same machine as the master but get a 'site can't be reached' error in chrome for localhost:39000. On higher ports the same amusing messages as in first post get pinged back to the browser. I also tried the same command replacing localhost with $(hostname -f) and connecting on localhost:39000 or replacing localhost with the hosname. No luck though.

```
$ /home/cryosparc2/installation/cryosparc2_worker/bin/cryosparcw connect localhost localhost 39000
 ---------------------------------------------------------------
Attempting to register worker localhost to command localhost:39002
Connecting as unix user cryosparc2
Will register using ssh string: cryosparc2@localhost
If this is incorrect, you should re-run this command with the flag --sshstr <ssh string> 
 ---------------------------------------------------------------
Connected to master.
 ---------------------------------------------------------------
Autodetecting available GPUs...
 Detected 2 CUDA devices.

 id           pci-bus  name
 ---------------------------------------------------------------
     0      0000:01:00.0  GeForce GTX 1080 Ti
     1      0000:02:00.0  GeForce GTX 1080 Ti
 ---------------------------------------------------------------
 All devices will be enabled now. You can disable them later.
 ---------------------------------------------------------------
Autodetecting the amount of RAM available...
 This machine has 32.09GB RAM .
 ---------------------------------------------------------------
Registering worker...
Done.

You can now launch jobs on the master node and they will be scheduled
on to this worker node if resource requirements are met.
 ---------------------------------------------------------------

```

**Comment by suhaildawood** [comment]
If you're using another computer to connect to the web application, you'll need to create an ssh tunnel to port 39000 on the machine running cryoSPARC v2 master.

**Comment by kylelmorris** [comment]
This is all on the same machine running the master and the worker. I should be able to connect with localhost:39000 after starting the master and the worker on the same local machine right?

**Comment by suhaildawood** [comment]
That's correct. Did you encounter any errors installing the master instance? What's the output of `cryosparcm log webapp`?

**Comment by kylelmorris** [comment]
```
$ cryosparcm log webapp
tail: cannot open ‘run/webapp.log’ for reading: No such file or directory
```

webapp.log wasn't present in the run directory. The command you suggested was helpful to notice something was wrong with the master installation, I didn't originally notice errors when installing the master but something must have been up.

Reinstalled the master instance and now after registering the worker can get in via chrome and localhost:39000.

Thank you!!

**Comment by suhaildawood** [comment]
Awesome! Closing this issue.
